# Generated by Django 5.0.3 on 2024-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestImage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
