# Generated by Django 5.0.3 on 2024-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_request_complainttype_alter_request_complaintby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='complaintType',
            field=models.TextField(),
        ),
    ]
