# Generated by Django 5.0.3 on 2024-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_request_complainttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='complaintBy',
            field=models.IntegerField(),
        ),
    ]
