# Generated by Django 5.0.3 on 2024-03-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_request_complaintby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
