# Generated by Django 5.0.3 on 2024-03-19 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestBy', models.IntegerField(null=True)),
                ('complaintType', models.TextField(null=True)),
                ('requestDetails', models.TextField()),
                ('requestDate', models.DateField(default=datetime.date(2024, 3, 19))),
                ('requestImage', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
