# Generated by Django 5.0.3 on 2024-03-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestDate',
            field=models.DateField(null=True),
        ),
    ]
