# Generated by Django 5.0.3 on 2024-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_requesttype_request_complainttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='complaintType',
            new_name='requestType',
        ),
    ]
