# Generated by Django 5.0.3 on 2024-03-19 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_complainttype_request_requesttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestDate',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
    ]
