# Generated by Django 5.0.3 on 2024-03-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_request_requestdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
