# Generated by Django 5.0.3 on 2024-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestImage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
