# Generated by Django 5.0.3 on 2024-03-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_request_requestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestDate',
            field=models.DateField(null=True),
        ),
    ]
