# Generated by Django 5.0.3 on 2024-03-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_request_requestdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestHandleDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestDate',
            field=models.DateField(default=datetime.date(2024, 3, 20)),
        ),
    ]
